### ISSUE TITLE
What do I have to answer to install actions or plugins?

### ISSUE THREAD

**Issue by jeroendesloovere** [turanct/forkmodule-cli#75]
![schermafbeelding 2015-06-09 om 09 31 07](https://cloud.githubusercontent.com/assets/588616/8052698/54934b3e-0e8a-11e5-8855-55b1839793d9.png)

... What do I have to answer to get anything installed?

**Comment by turanct** [comment]
The name of the widget or action, for instance `index`, `detail`, etc...

**Comment by jeroendesloovere** [comment]
Thanks :+1:
